#ymlをpushしてpropertiesになるかどうか shogi Connectcrew@123
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shogi?serverTimezone=UTC&useSSL=false
    username: root
    password: qwerty1
    driver-class-name: com.mysql.cj.jdbc.Driver