#ymlをpushしてpropertiesになるかどうか
spring:
  datasource:
    url: jdbc:mysql://192.168.11.17:3306/shogi?serverTimezone=UTC&useSSL=false
    username: shogi
    password: Connectcrew@123
    driver-class-name: com.mysql.cj.jdbc.Driver