spring:
  datasource:
    url: jdbc:mysql://192.168.11.15:3306/goodspot?serverTimezone=UTC&useSSL=false
    username: shogi
    password: Connectcrew@123
    driver-class-name: com.mysql.jdbc.Driver